title: Warwick Cyber Security Society
description: Welcome to the Warwick Cyber Security Society!. We're a friendly and inclusive community centred around our love of Cyber Security.
discordURL: https://discord.gg/Ys4fr5CMKj
instagramURL: https://www.instagram.com/warwickcybersoc/
twitterURL: https://twitter.com/warwickcybersoc
githubURL: https://www.github.com/warwickcybersoc/
email: contact@warwickcybersoc.com
societyURL: https://www.warwicksu.com/societies-sports/societies/61481/
exec:
  - name: Peter Walker
    role: President
  - name: Oscar Topliss
    role: Vice President
  - name: Ellie Baxter
    role: Treasurer
  - name: Oscar Innes
    role: Welfare Officer
  - name: Samuel Kamas
    role: Technician
  - name: Abi Lowrie
    role: Women's Officer
  - name: Artem Polovnev
    role: External Communications Officer
  - name: Jamie Madden
    role: Social Secretary
  - name: Tom Slater
    role: Social Secretary
  - name: Samuel Kamas
    role: Marketing Officer
navbar:
  - name: Home
    link: /
  - name: Events
    link: /events
  - name: Resources
    link: /resources
  - name: Sponsors
    link: /sponsors

achievements:
  - title: "#1 - pwnEd6 CTF Qualifiers (2025)"
    year: 2025
  - title: "#2 - pwnEd5 CTF (2024)"
    year: 2024
  - title: "#1 - SAT UK&TR International CTF (2024)"
    year: 2024
  - title: "#1 - pwnEd2 CTF (2021)"
    year: 2021
  - title: "#1 - HTB x UNI CTF Qualifiers (2021)"
    year: 2021
  - title: "#1 - Veracode The Hacker Games (2021)"
    year: 2021
 
googleCalendarAPIKey: "AIzaSyB4zs2Pj-03aUlL5CHiRwU-PYVZR8glej0"
googleCalendarID: "cb123093dad94d416cca0dab4107fac28aee675270cad0e082b8e7d35945df0a@group.calendar.google.com"
googleCalendarURL: "https://calendar.google.com/calendar/embed?src=cb123093dad94d416cca0dab4107fac28aee675270cad0e082b8e7d35945df0a%40group.calendar.google.com&ctz=Europe%2FLondon"

resources:
  - title: "Warwick Cyber Security Society GitHub"
    description: "Our GitHub repository, where we store all of our resources and write-ups."
    link: "https://github.com/WarwickCyberSoc"

posts:
  - title: "Intake CTF 2023"
    author: "Tom Steer"
    link: "https://tomsteer.com/posts/intakectf23/"
  - title: "Intake 2023 Writeups"
    author: "Oscar Sharpe"
    link: "https://oscarsharpe.me/posts/intake-writeup"

sponsors:
  - name: "Crowdstrike"
    link: "https://www.crowdstrike.com/en-gb/"
    image: "https://warwickcybersoc.com/images/CS_Logo_Cropped.png"
    description: "#WeAreCrowdStrike and our mission is to stop breaches. As a global leader in cybersecurity, our team has changed the game. Since our inception in 2011, our market leading cloud-native platform has offered unparalleled protection against the most sophisticated cyberattacks. It combines the most advanced endpoint protection with expert intelligence to pinpoint the adversaries perpetrating the attacks, not just the malware."
  - name: "Interrupt Labs"
    link: "https://www.interruptlabs.co.uk/"
    image: "https://warwickcybersoc.com/images/IL_Logo.png"
    description: "Interrupt Labs is a leading vulnerability research company working on some of the toughest challenges in the industry from popping browsers to exploiting phones and cars. We cover it all with an exceptional team of vulnerability researchers. We are always on the lookout for talented people; whether you are early on in your career, or you already know your way around IDA, we are keen to talk research."
